version: "3"
services:
  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: Password1!
    ports:
      - 1433:1433
    volumes:
      - ./mssql-data:/var/opt/mssql
